Novactive/Nova-eZPlatform-Bundles

README.md, components/Accelerator/documentation/INSTALL.md, components/CloudinaryBundle/Core/AliasGenerator.php, components/CloudinaryBundle/Core/ImageVariation.php, components/CloudinaryBundle/DependencyInjection/Configuration.php, components/CloudinaryBundle/DependencyInjection/NovaeZCloudinaryExtension.php, components/CloudinaryBundle/NovaeZCloudinaryBundle.php, components/CloudinaryBundle/README.md, components/CloudinaryBundle/Resources/config/field_override.yml, components/CloudinaryBundle/Resources/config/services.yml, components/CloudinaryBundle/Resources/views/content_fields.html.twig, components/CloudinaryBundle/Twig/Extension.php, components/CloudinaryBundle/ci-config.yaml, components/CloudinaryBundle/composer.json, components/CloudinaryBundle/tests/provisioning/bundles.yaml, components/CloudinaryBundle/tests/provisioning/configs.yaml, components/ExtraBundle/README.md, components/ProtectedContentBundle/tests/provisioning/article.html.twig
=> Cloudinary Bundle for 3.x

components/ExtraBundle/bundle/Resources/config/services.yaml
=> add config Twig Content Extension

components/SEOBundle/bundle/Core/MetaNameSchema.php, components/SEOBundle/bundle/Resources/views/fields/novaseometas.html.twig, components/SEOBundle/bundle/Twig/NovaeZSEOExtension.php
Hello @Plopix,
I would like to suggest for you this improvement of the the filter `computeMetas`, If we use `content` rather than `contentInfo`, can helps us to avoid many fetch data.
Ramtane.
=> SEOBundle : optimization of the extension NovaeESEOExtension

components/ExtraBundle/bundle/Twig/ContentExtension.php
=> fix if content related is still in trash

components/ProtectedContentBundle/bundle/Core/SiteAccessAwareEntityManagerFactory.php, components/ProtectedContentBundle/bundle/Resources/config/services.yaml
=> Add ProtectedContentBundle SiteAccessAwareEntityManagerFactory

components/2FABundle/README.md, components/2FABundle/bundle/Command/Remove2FAForUserCommand.php, components/2FABundle/bundle/Controller/TwoFactorAuthController.php, components/2FABundle/bundle/Listener/TwoFactorAuthenticationEventSubscriber.php, components/2FABundle/bundle/Resources/config/services.yaml, components/2FABundle/bundle/Resources/views/themes/standard/2fa/auth.html.twig, components/2FABundle/bundle/Resources/views/themes/standard/2fa/setup.html.twig, components/2FABundle/tests/provisioning/configs.yaml
=> 2FA - Trusted Device

components/SEOBundle/bundle/Core/SiteAccessAwareEntityManagerFactory.php
| Fixed tickets | #44 
With this PR backend features for importing urls will work again.
=> Bugfix import urls features in backend

.github/workflows/main-ci.yaml, Makefile
=> Updated the ibexa installation on make file and github action

components/2FABundle/README.md, components/2FABundle/bundle/Controller/TwoFactorAuthController.php, components/2FABundle/bundle/Core/SiteAccessAwareAuthenticatorResolver.php, components/2FABundle/bundle/Core/Tab/TwoFAManagement.php, components/2FABundle/bundle/Core/UserRepository.php, components/2FABundle/bundle/DependencyInjection/Security/PolicyProvider.php, components/2FABundle/bundle/Entity/AuthenticatorInterface.php, components/2FABundle/bundle/Entity/BackupCodeAware.php, components/2FABundle/bundle/Entity/BackupCodeInterface.php, components/2FABundle/bundle/Entity/UserGoogleAuthSecret.php, components/2FABundle/bundle/Entity/UserTotpAuthSecret.php, components/2FABundle/bundle/NovaeZ2FABundle.php, components/2FABundle/bundle/Resources/config/policies.yaml, components/2FABundle/bundle/Resources/config/routing.yaml, components/2FABundle/bundle/Resources/config/services.yaml, components/2FABundle/bundle/Resources/sql/schema.sql, components/2FABundle/bundle/Resources/views/themes/standard/2fa/setup.html.twig, components/2FABundle/bundle/Resources/views/themes/standard/2fa/tabs/reset_for_user.html.twig, components/2FABundle/bundle/Security/BackupCodeManager.php, components/2FABundle/composer.json
=> 2fa - added backup codes and manual reset features

components/2FABundle/README.md, components/2FABundle/tests/provisioning/configs.yaml
=> 2FA fix config, update readme

components/2FABundle/README.md
=> 2fa readme updated - 1.4.3 patch

components/2FABundle/README.md, components/2FABundle/bundle/Resources/views/themes/standard/2fa/auth.html.twig
=> 2FA patch 144

.github/workflows/main-ci.yaml
=> fix: set nodejs version to 14 in github action to prevent error

src/Command/AskValidComponent.php, src/Command/SyncCommand.php
=> feat: update the sync command to make it possible to sync only a specified component

components/EnhancedImageAssetBundle/src/bundle/DependencyInjection/EzEnhancedImageAssetExtension.php, components/EnhancedImageAssetBundle/src/bundle/Resources/config/services.yml, components/EnhancedImageAssetBundle/src/bundle/Resources/views/themes/standard/enhanced_image_asset/content_fields.html.twig, components/EnhancedImageAssetBundle/src/lib/Imagine/AliasDirectoryVariationPathGenerator.php, components/EnhancedImageAssetBundle/src/lib/Imagine/Filter/FilterConfiguration.php, components/EnhancedImageAssetBundle/src/lib/Imagine/Filter/Loader/ToFormatFilterLoader.php, components/EnhancedImageAssetBundle/src/lib/Twig/ImageExtension.php
| Branch?       | feat-enhancedimage-ibx3
| New feature?  | yes
| Fixed tickets | #96954
- création automatique des variations webp
NB: l'extension de l'image reste la même que l'original, mais le format est bien webp
=> feat: #96954 - Implémentation des variations d'images (Webp et Jpeg)

composer.lock
| Branch?       | master-bx3
| Fixed tickets | https://github.com/Novactive/Nova-eZPlatform-Bundles/security/dependabot/3
=> Fix dependabot alert

.github/workflows/main-ci.yaml
=> feat: change tests to be done on ibexa OSS 4

components/SolrSearchExtraBundle/src/bundle/DependencyInjection/EzSolrSearchExtraExtension.php, components/SolrSearchExtraBundle/src/bundle/EzSolrSearchExtraBundle.php, components/SolrSearchExtraBundle/src/bundle/Resources/config/services.yml, components/SolrSearchExtraBundle/src/bundle/Resources/config/taxonomy_aggregator.yml, components/SolrSearchExtraBundle/src/bundle/Resources/views/themes/admin/solr/admin/dashboard.html.Twig, components/SolrSearchExtraBundle/src/bundle/Resources/views/themes/admin/solr/admin/stopwords/list.html.Twig, components/SolrSearchExtraBundle/src/bundle/Resources/views/themes/admin/solr/admin/synonyms/list.html.Twig, components/SolrSearchExtraBundle/src/lib/ApiLoader/GatewayFactory.php, components/SolrSearchExtraBundle/src/lib/Container/Compiler/EndpointResolverPass.php, components/SolrSearchExtraBundle/src/lib/FieldMapper/BinaryFileFieldMapper.php, components/SolrSearchExtraBundle/src/lib/FieldMapper/ContentTranslationFieldMapper/BinaryFileFullTextFieldMapper.php, components/SolrSearchExtraBundle/src/lib/FieldMapper/ContentTranslationFieldMapper/CustomFieldMapper.php, components/SolrSearchExtraBundle/src/lib/FieldMapper/ContentTranslationFieldMapper/PublishDateFieldMapper.php, components/SolrSearchExtraBundle/src/lib/Query/Aggregation/RawTermAggregation.php, components/SolrSearchExtraBundle/src/lib/Query/Aggregation/TaxonomyRawTermAggregation.php, components/SolrSearchExtraBundle/src/lib/Query/AggregationResultExtractor/AggregationKeyMapper/RawTermAggregationKeyMapper.php, components/SolrSearchExtraBundle/src/lib/Query/AggregationResultExtractor/AggregationKeyMapper/TaxonomyRawTermAggregationKeyMapper.php, components/SolrSearchExtraBundle/src/lib/Query/AggregationResultExtractor/RawTermAggregationResultExtractor.php, components/SolrSearchExtraBundle/src/lib/Query/AggregationVisitor/RawTermAggregationVisitor.php, components/SolrSearchExtraBundle/src/lib/Query/Common/FacetBuilder/CustomFieldFacetBuilder.php, components/SolrSearchExtraBundle/src/lib/Query/Content/CriterionVisitor/FilterTag.php, components/SolrSearchExtraBundle/src/lib/Search/AggregationResult/RawTermAggregationResult.php, components/SolrSearchExtraBundle/src/lib/Search/AggregationResult/RawTermAggregationResultEntry.php
=> feat: add custom field aggregations for ibexa 4

components/MaintenanceBundle/bundle/Resources/config/services.yaml
=> NovaeZMaintenanceBundle Fix Admin Url

components/SolrSearchExtraBundle/src/bundle/DependencyInjection/EzSolrSearchExtraExtension.php, components/SolrSearchExtraBundle/src/bundle/Resources/config/aggregators.yml, components/SolrSearchExtraBundle/src/lib/Query/Aggregation/RawTermAggregation.php, components/SolrSearchExtraBundle/src/lib/ResultExtractor/AggregationKeyMapper/AbstractRawTermAggregationKeyMapper.php, components/SolrSearchExtraBundle/src/lib/ResultExtractor/AggregationKeyMapper/RawTermAggregationKeyMapper.php, components/SolrSearchExtraBundle/src/lib/ResultExtractor/AggregationKeyMapper/TaxonomyRawTermAggregationKeyMapper.php, components/SolrSearchExtraBundle/src/lib/ResultExtractor/RawTermAggregationResultExtractor.php, components/SolrSearchExtraBundle/src/lib/Search/AggregationResult/RawTermAggregationResultEntry.php
=> add raw term aggregation config

components/2FABundle/bundle/Controller/TwoFactorAuthController.php, components/2FABundle/bundle/Core/SiteAccessAwareAuthenticatorResolver.php, components/2FABundle/bundle/Resources/config/services.yaml
| Branch?       | 2fa-ibexa-4.0
| Fixed tickets | https://almaviacx.easyredmine.com/issues/105021
=> Fix bug siteaccess default value, add lazy and remove final

components/MenuManagerBundle/src/bundle/Controller/AdminController.php, components/MenuManagerBundle/src/bundle/Controller/ViewController.php, components/MenuManagerBundle/src/bundle/Resources/config/ezadminui/components.yml, components/MenuManagerBundle/src/bundle/Resources/config/field_value_converters.yml, components/MenuManagerBundle/src/bundle/Resources/config/fieldtypes.yml, components/MenuManagerBundle/src/bundle/Resources/config/indexable_fieldtypes.yml, components/MenuManagerBundle/src/bundle/Resources/config/services.yml, components/MenuManagerBundle/src/bundle/Resources/encore/ez.config.js, components/MenuManagerBundle/src/bundle/Resources/views/themes/admin/menu_manager/view.html.twig, components/MenuManagerBundle/src/bundle/Resources/views/themes/standard/field_type/field_types.html.twig, components/MenuManagerBundle/src/bundle/Resources/views/themes/standard/menu_manager/admin/edit.html.twig, components/MenuManagerBundle/src/bundle/Resources/views/themes/standard/menu_manager/admin/form_fields.html.twig, components/MenuManagerBundle/src/bundle/Resources/views/themes/standard/menu_manager/admin/list.html.twig, components/MenuManagerBundle/src/lib/EventListener/AssignSectionToSubtreeSignalSlot.php, components/MenuManagerBundle/src/lib/EventListener/CachePurgerTrait.php, components/MenuManagerBundle/src/lib/EventListener/PublishVersionSignalSlot.php, components/MenuManagerBundle/src/lib/Form/Type/FieldType/MenuItemFieldType.php, components/MenuManagerBundle/src/lib/Form/Type/MenuRootLocationType.php, components/MenuManagerBundle/src/lib/Form/Type/MenuSearchType.php, components/MenuManagerBundle/src/lib/Form/Type/MenuType.php, components/MenuManagerBundle/src/lib/MenuItem/Type/ContentMenuItemType.php, components/MenuManagerBundle/src/lib/MenuItem/Type/DefaultMenuItemType.php, components/MenuManagerBundle/src/lib/Migration/ReferenceResolver/CustomReferenceResolver.php, components/MenuManagerBundle/src/lib/Service/MenuCacheService.php, components/MenuManagerBundle/src/lib/Service/MenuService.php, components/MenuManagerBundle/src/lib/Twig/MenuManagerExtension.php
=> EzMenuManager Migration ibexa 4

components/ProtectedContentBundle/bundle/Core/SiteAccessAwareEntityManagerFactory.php, components/RssFeedBundle/src/bundle/Core/SiteAccessAwareEntityManagerFactory.php
=> fix: SiteAccessAwareEntityManagerFactory

components/ProtectedContentBundle/bundle/Core/Tab/ProtectContent.php, components/ProtectedContentBundle/bundle/Entity/ProtectedAccess.php, components/ProtectedContentBundle/bundle/Listener/PreContentView.php
=> fix: ProtectedAccess repository

components/SEOBundle/bundle/Command/AddNovaSEOMetasFieldTypeCommand.php, components/SEOBundle/bundle/Core/Installer/Field.php, components/SEOBundle/bundle/DependencyInjection/NovaeZSEOExtension.php, components/SEOBundle/bundle/Form/Type/MetaType.php, components/SEOBundle/bundle/Resources/config/services.yml, components/SEOBundle/documentation/CHANGELOG.md, components/SEOBundle/documentation/INSTALL.md, components/SEOBundle/documentation/USAGE.md
=> Fixed siteaccess aware for multisite

components/EnhancedImageAssetBundle/src/bundle/Resources/config/services.yml
=> fix: placeholder provider config

components/SolrSearchExtraBundle/src/lib/Query/Common/FacetBuilder/CustomFieldFacetBuilder.php, components/SolrSearchExtraBundle/src/lib/Query/Common/FacetBuilderVisitor/CustomField.php
https://github.com/Novactive/NovaeZSolrSearchExtraBundle/commit/93f8b0b0eabd390192a9f81b077969f6ade43714
=> feat: added a way to specify the excludeTerms facet param

components/SolrSearchExtraBundle/src/lib/ResultExtractor/AggregationKeyMapper/AbstractRawTermAggregationKeyMapper.php
=> fix raw term aggregation

.github/workflows/main-ci.yaml, bin/wrapbundle, components/SEOBundle/bundle/Resources/sql/schema.sql, components/SEOBundle/tests/Tests/SEOControllerPantherTest.php, composer.json, composer.lock, tests/Tests/PantherTestCase.php
=> fix: switch CI env to prod

components/RssFeedBundle/src/bundle/Resources/public/admin/js/collection_rss.js, components/RssFeedBundle/src/bundle/Resources/views/themes/admin/rssfeed/edit.html.twig
=> Fix rss feed collection js

components/RssFeedBundle/src/bundle/Form/RssFeedsType.php, components/RssFeedBundle/src/bundle/Resources/public/admin/js/collection_rss.js, components/RssFeedBundle/src/bundle/Resources/views/Form/form_fields.html.twig, components/RssFeedBundle/src/bundle/Resources/views/themes/admin/rssfeed/edit.html.twig
=> fix: js error while adding feed items

components/ProtectedContentBundle/bundle/Resources/views/themes/admin/tabs/protected_content.html.twig
| Branch?       | master (For Ibexa4)
| Fixed tickets | [#106733 - novactive/ezprotectedcontentbundle - gestion de la protection par mot de passe d'un contenu](https://almaviacx.easyredmine.com/issues/106733)
=> ezprotectedcontentbundle - Fix admin modal

components/ProtectedContentBundle/bundle/Controller/Admin/ProtectedAccessController.php, components/ProtectedContentBundle/bundle/Resources/config/services.yaml
novactive/ezprotectedcontentbundle
Correction de la suppression des access
| Fixed tickets | [#... ](https://almaviacx.easyredmine.com/issues/106733)
=> #106733 - novactive/ezprotectedcontentbundle - gestion de la protection par mot de passe d'un contenu

components/ProtectedContentBundle/bundle/Listener/PreContentView.php
| Branch?       | master (Ibexa 4)
| Fixed tickets |
=> fix preview

components/ExtraBundle/bundle/EventListener/PreContentViewListener.php, components/ExtraBundle/bundle/EventListener/Type.php
=> FIX errors in eZExtraBundle Ibexa 4 migration

.github/workflows/main-ci.yaml
=> feat: update volta-cli in CI

.cs/md_ruleset.xml, components/SEOBundle/bundle/Core/Sitemap/QueryFactory.php
https://github.com/Novactive/Nova-eZPlatform-Bundles/pull/135
=> Fix sitemap include

components/RssFeedBundle/src/bundle/Resources/views/themes/standard/rssfeed/view.html.twig
=> Fix format XML

composer.json
=> fix: set dbrekelmans/bdi version to work with php 7

components/SEOBundle/bundle/Core/MetaNameSchema.php
=> Fix render meta when content image not found

components/StaticTemplatesBundle/bundle/Routing/Router.php
=> fix: issue while generating url on static siteaccesses

components/TranslationUiBundle/src/lib/Translation/Translator.php
https://almaviacx.easyredmine.com/issues/111238
Quand on fait des modifications dans le translation manager ça ne change rien en front.
=> #111238 - Renouveler le cache des traductions

components/MenuManagerBundle/src/bundle/Controller/AdminController.php, components/MenuManagerBundle/src/bundle/Resources/config/ezadminui/components.yml, components/MenuManagerBundle/src/bundle/Resources/translations/menu_manager.en.yml, components/MenuManagerBundle/src/bundle/Resources/translations/menu_manager.fr.yml, components/MenuManagerBundle/src/bundle/Resources/translations/messages.en.yml, components/MenuManagerBundle/src/bundle/Resources/translations/messages.fr.yml, components/MenuManagerBundle/src/bundle/Resources/views/themes/admin/menu_manager/view.html.twig, components/MenuManagerBundle/src/bundle/Resources/views/themes/standard/menu_manager/admin/edit.html.twig, components/MenuManagerBundle/src/bundle/Resources/views/themes/standard/menu_manager/admin/list.html.twig, components/MenuManagerBundle/src/lib/AdminUI/Menu/MenuItemEditRightSidebarBuilder.php, components/MenuManagerBundle/src/lib/Form/Type/MenuSearchType.php, components/MenuManagerBundle/src/lib/Form/Type/MenuType.php
=> fix:remove cta modal && admin ui enhacment

components/RssFeedBundle/src/bundle/Controller/Admin/RssFeedController.php, components/RssFeedBundle/src/bundle/Resources/translations/messages.en.yml, components/RssFeedBundle/src/bundle/Resources/translations/messages.fr.yml, components/RssFeedBundle/src/bundle/Resources/views/themes/admin/rssfeed/list.html.twig, components/RssFeedBundle/src/bundle/Resources/views/themes/standard/rssfeed/view.html.twig
remove ParamConverter
| Fixed tickets | [#106734 - [MIG IBEXA] novactive/ezrssfeedbundle - gestion de flux rss](https://almaviacx.easyredmine.com/issues/106734)
=> #106734 - [MIG IBEXA] novactive/ezrssfeedbundle - gestion de flux rss

components/ExtraBundle/README.md, components/ExtraBundle/bundle/Contracts/RouterAware.php
=> FIX urlalias in eZExtraBundle Ibexa 4 migratio

components/ExtraBundle/bundle/Resources/views/Picture/alias.html.twig
=> FIX change ez_is_field_empty ibexa4 migration

components/ExtraBundle/bundle/Twig/ImageExtension.php
=> FIX image placeholder ibexa4 migration

components/MaintenanceBundle/bundle/Listener/MaintenanceSubscriber.php
| Fixed tickets | #110755 #115005
// In case front siteaccess locked
// Include request used in preview mode page builder
=> Feat 110755 fix preview admin locked front siteaccess

components/MenuManagerBundle/src/lib/FieldType/MenuItem/Type.php
| Branch?       | feat-menumanager-ibx4-fix-use-value
| BC breaks?    | yes
| Fixed tickets | 116241
=> Fix error in use ../value in Type.php. Missing majuscule.

components/RssFeedBundle/src/bundle/Controller/Admin/RssFeedController.php, components/RssFeedBundle/src/bundle/Resources/views/themes/admin/rssfeed/list.html.twig
| Branch?       | ezrssfeedbundle-fix-error-on-delete
| Fixed tickets | 116360
> Detached entity Novactive\EzRssFeedBundle\Entity\RssFeedItems@4900 cannot be removed
=> Fix Error on delete RssFeeds

components/StaticTemplatesBundle/bundle/DependencyInjection/EzStaticTemplatesExtension.php, components/StaticTemplatesBundle/bundle/Resources/config/default_parameters.yaml
=> fix: remove static siteaccesses from preview siteaccess list

.github/workflows/main-ci.yaml, components/EnhancedImageAssetBundle/src/lib/FieldType/EnhancedImage/FormMapper.php, components/MaintenanceBundle/bundle/Listener/MaintenanceSubscriber.php, components/RssFeedBundle/src/bundle/Controller/Admin/RssFeedController.php, components/SEOBundle/bundle/Core/MetaNameSchema.php
=> feat: switch to node 18 for new ibexa versions in order to fix CI

components/RichTextExtraBundle/src/bundle/Resources/public/js/CKEditor/upload-file/upload-file-editing.js
| Branch?       | `feat-richtext-extra`
| BC breaks?    | yes/no yes ?
| Fixed tickets | 117312 #...
=> Fix conflict between drop file en image

components/EnhancedImageAssetBundle/src/lib/Imagine/FocusedImageAliasGenerator.php, components/EnhancedImageAssetBundle/src/lib/Imagine/ImageAliasGenerator.php
=> fixe: issue with webp variation not taking the focuspoint into account

components/EnhancedImageAssetBundle/src/lib/FieldType/EnhancedImage/FormMapper.php
=> fix: enhancedimage field form mapper missing interface

components/ProtectedContentBundle/bundle/Listener/PreContentView.php
| Branch?       | `feat-108625-ibexa-4-form-mail-protection`
| Fixed tickets | #119150
=> No protection with preview

bin/ci-should, components/SEOBundle/bundle/Core/FieldType/Metas/FormMapper.php, components/SEOBundle/bundle/Core/MetaNameSchema.php, components/SEOBundle/bundle/DependencyInjection/NovaeZSEOExtension.php, components/SEOBundle/bundle/Form/Type/MetaType.php, components/SEOBundle/bundle/Resources/config/ibexa.yaml, components/SEOBundle/ci-config.yaml, components/SEOBundle/composer.json
=> Ibexa 4.6 seo

components/MenuManagerBundle/src/bundle/Resources/translations/ibexa_menu.en.yml, components/MenuManagerBundle/src/bundle/Resources/translations/ibexa_menu.fr.yml
Add ibexa_menu.*.yml translation file
Base on `masteribexa-4-master`
See #197 for branch base on `ibexa-4-master`
| Fixed tickets | #119677
=> Add ibexa_menu.*.yml translation file (master)

components/SamlBundle/README.md, components/SamlBundle/src/bundle/AlmaviaCXIbexaSamlBundle.php, components/SamlBundle/src/bundle/DependencyInjection/Compiler/LazySaml2Auth.php, components/SamlBundle/src/bundle/Resources/config/services.yaml, components/SamlBundle/src/lib/Security/Saml/SamlAuthFactory.php
=> feat: add support for siteaccess aware configuration

components/SolrSearchExtraBundle/src/bundle/Resources/translations/ibexa_menu.en.yml, components/SolrSearchExtraBundle/src/bundle/Resources/translations/ibexa_menu.fr.yml
Add ibexa_menu.*.yml translation file
| Fixed tickets | #119677
=> [ezsolrsearchextrabundle] Add ibexa_menu.*.yml translation file

components/TranslationUiBundle/src/bundle/Resources/translations/ibexa_menu.en.yml, components/TranslationUiBundle/src/bundle/Resources/translations/ibexa_menu.fr.yml
#119677
| Fixed tickets | #119677
=> [ibexatranslationuibundle] Add ibexa_menu.*.yml translation file

components/SEOBundle/bundle/Core/UrlWildcardRouter.php
| Branch?       | master-ibexa-4.5
=> fix: issue with redirect where source is a siteaccess with en URI match

components/SolrSearchExtraBundle/src/lib/Query/Content/Criterion/MultipleFieldsFullText.php, components/SolrSearchExtraBundle/src/lib/Query/Content/CriterionVisitor/MultipleFieldsFullText.php
=> feat: add boost query parameter to MultipleFieldsFullText criterion

components/2FABundle/bundle/Command/Remove2FAForUserCommand.php, components/2FABundle/bundle/Core/AuthCodeMailer.php, components/2FABundle/bundle/Core/BackupCodeManager.php, components/2FABundle/bundle/Core/EmailCodeGenerator.php, components/2FABundle/bundle/Core/QRCodeGenerator.php, components/2FABundle/bundle/Core/SiteAccessAwareAuthenticatorResolver.php, components/2FABundle/bundle/Core/SiteAccessAwareQueryExecutor.php, components/2FABundle/bundle/Core/UserRepository.php, components/2FABundle/bundle/DependencyInjection/Configuration.php, components/2FABundle/bundle/Entity/BackupCodeAware.php, components/2FABundle/bundle/Entity/UserEmailAuth.php, components/2FABundle/bundle/Entity/UserTotpAuthSecret.php, components/2FABundle/bundle/Listener/MenuEventSubscriber.php, components/2FABundle/bundle/Listener/OnHttpRequestListener.php, components/2FABundle/bundle/Listener/TwoFactorAuthenticationEventSubscriber.php, components/2FABundle/bundle/Listener/UserEventSubscriber.php, components/2FABundle/bundle/Security/TwoFactorUserProviderDecorator.php, components/2FABundle/composer.json
=> * ibexa4.6 : eZ2FABundle Migration [support php>=8.1]

components/CaptchEtatBundle/LICENSE, components/CaptchEtatBundle/README.md, components/CaptchEtatBundle/ci-config.yaml, components/CaptchEtatBundle/composer.json, components/CaptchEtatBundle/src/bundle/AlmaviaCXCaptchEtatBundle.php, components/CaptchEtatBundle/src/bundle/Controller/CaptchEtatController.php, components/CaptchEtatBundle/src/bundle/DependencyInjection/AlmaviaCXCaptchEtatExtension.php, components/CaptchEtatBundle/src/bundle/Resources/config/default_settings.yaml, components/CaptchEtatBundle/src/bundle/Resources/config/routes.yaml, components/CaptchEtatBundle/src/bundle/Resources/config/services.yaml, components/CaptchEtatBundle/src/bundle/Resources/public/js/captchetat-widget.js, components/CaptchEtatBundle/src/bundle/Resources/templates/captchetat-fields.html.twig, components/CaptchEtatBundle/src/bundle/Resources/translations/captchetat.en.yaml, components/CaptchEtatBundle/src/bundle/Resources/translations/captchetat.fr.yaml, components/CaptchEtatBundle/src/bundle/Resources/translations/messages.en.yaml, components/CaptchEtatBundle/src/bundle/Resources/translations/messages.fr.yaml, components/CaptchEtatBundle/src/lib/Api/Gateway.php, components/CaptchEtatBundle/src/lib/Api/OauthGateway.php, components/CaptchEtatBundle/src/lib/Challenge/ChallengeGenerator.php, components/CaptchEtatBundle/src/lib/Challenge/ChallengeValidator.php, components/CaptchEtatBundle/src/lib/Exceptions/MissingConfigurationException.php, components/CaptchEtatBundle/src/lib/Form/Type/CaptchEtatType.php, components/CaptchEtatBundle/src/lib/FormBuilder/FieldType/Field/Mapper/ButtonFieldMapperDecorator.php, components/CaptchEtatBundle/src/lib/Logger/CaptchEtatLogger.php, components/CaptchEtatBundle/src/lib/Validator/CaptchEtatChallengeValidator.php, components/CaptchEtatBundle/src/lib/Validator/Constraint/CaptchEtatValidChallenge.php, components/CaptchEtatBundle/src/lib/Value/CaptchEtatChallenge.php
=> feat: CaptchEtat bundle

components/RssFeedBundle/README.md, components/RssFeedBundle/src/bundle/Controller/RssFeedViewController.php, components/RssFeedBundle/src/bundle/DependencyInjection/EzRssFeedExtension.php, components/RssFeedBundle/src/bundle/EventListener/DoctrineEventListener.php, components/RssFeedBundle/src/bundle/Resources/config/default_settings.yaml, components/RssFeedBundle/src/bundle/Resources/config/services.yml
=> feat: add HTTP cache support to RSS feeds

components/2FABundle/README.md, components/2FABundle/bundle/Command/Remove2FAForUserCommand.php, components/2FABundle/bundle/Controller/TwoFactorAuthController.php, components/2FABundle/bundle/Core/BackupCodeManager.php, components/2FABundle/bundle/Core/SiteAccessAwareAuthenticatorResolver.php, components/2FABundle/bundle/Core/SiteAccessAwareQueryExecutor.php, components/2FABundle/bundle/Core/Tab/TwoFAManagement.php, components/2FABundle/bundle/DependencyInjection/Configuration.php, components/2FABundle/bundle/DependencyInjection/NovaeZ2FAExtension.php, components/2FABundle/bundle/DependencyInjection/Security/PolicyProvider.php, components/2FABundle/bundle/Entity/UserEmailAuth.php, components/2FABundle/bundle/Entity/UserGoogleAuthSecret.php, components/2FABundle/bundle/Entity/UserTotpAuthSecret.php, components/2FABundle/bundle/Listener/MenuEventSubscriber.php, components/2FABundle/bundle/Listener/OnHttpRequestListener.php, components/2FABundle/bundle/Listener/UserEventSubscriber.php, components/2FABundle/bundle/NovaeZ2FABundle.php, components/2FABundle/bundle/Resources/config/services.yaml, components/2FABundle/bundle/Resources/views/themes/standard/2fa/auth.html.twig, components/2FABundle/bundle/Resources/views/themes/standard/2fa/auth/trusted_device.html.twig, components/2FABundle/bundle/Resources/views/themes/standard/2fa/setup.html.twig, components/2FABundle/bundle/Resources/views/themes/standard/2fa/tabs/reset_for_user.html.twig, components/2FABundle/bundle/Security/TwoFactorUserProviderDecorator.php, components/2FABundle/composer.json, components/2FABundle/tests/provisioning/configs.yaml
=> * 2fa support to ibexa 4.0

components/MenuManagerBundle/src/lib/MenuItem/Type/ContentMenuItemType.php, components/MenuManagerBundle/src/lib/MenuItem/Type/DefaultMenuItemType.php, components/MenuManagerBundle/src/modules/menu-manager/components/form/ContainerMenuItemEditFormModule.jsx, components/MenuManagerBundle/src/modules/menu-manager/components/form/MenuItemEditFormModule.jsx
=> Fix menu manager

components/ImportExportBundle/src/bundle/DependencyInjection/AlmaviaCXIbexaImportExportExtension.php, components/ImportExportBundle/src/bundle/Resources/config/taxonomy_services.yaml, components/ImportExportBundle/src/lib/Writer/Ibexa/Content/IbexaContentImporter.php, components/ImportExportBundle/src/lib/Writer/Ibexa/Taxonomy/IbexaTaxonomyCreator.php, components/ImportExportBundle/src/lib/Writer/Ibexa/Taxonomy/IbexaTaxonomyData.php, components/ImportExportBundle/src/lib/Writer/Ibexa/Taxonomy/IbexaTaxonomyImporter.php, components/ImportExportBundle/src/lib/Writer/Ibexa/Taxonomy/IbexaTaxonomyUpdater.php, components/ImportExportBundle/src/lib/Writer/Ibexa/Taxonomy/IbexaTaxonomyWriter.php, components/ImportExportBundle/src/lib/Writer/Ibexa/Taxonomy/IbexaTaxonomyWriterOptions.php
=> feat: Ibexa Taxonomy writer

components/ImportExportBundle/src/bundle/Controller/Admin/JobController.php, components/ImportExportBundle/src/bundle/Resources/config/routes.yaml, components/ImportExportBundle/src/bundle/Resources/translations/forms.en.yaml, components/ImportExportBundle/src/bundle/Resources/translations/import_export.en.yaml, components/ImportExportBundle/src/bundle/Resources/translations/import_export.fr.yaml, components/ImportExportBundle/src/bundle/Resources/translations/messages.en.yaml, components/ImportExportBundle/src/bundle/Resources/views/themes/admin/import_export/job/list.html.twig, components/ImportExportBundle/src/bundle/Resources/views/themes/admin/import_export/job/view.html.twig, components/ImportExportBundle/src/lib/Job/AbstractJobRunner.php, components/ImportExportBundle/src/lib/Job/Job.php, components/ImportExportBundle/src/lib/Job/JobRunner.php, components/ImportExportBundle/src/lib/Job/JobService.php, components/ImportExportBundle/src/lib/Workflow/AbstractWorkflow.php, components/ImportExportBundle/src/lib/Workflow/WorkflowEvent.php
=> feat: added a way to cancel a job

components/ImportExportBundle/bin/mdb-to-sqlite.bash, components/ImportExportBundle/src/bundle/Resources/config/workflow/component.yaml, components/ImportExportBundle/src/bundle/Resources/views/themes/admin/import_export/job/view.html.twig, components/ImportExportBundle/src/lib/Component/ComponentBuilder.php, components/ImportExportBundle/src/lib/Component/ComponentOptions.php, components/ImportExportBundle/src/lib/Item/ValueTransformer/Utils/SlugTransformer.php, components/ImportExportBundle/src/lib/Job/Job.php, components/ImportExportBundle/src/lib/Processor/Aggregator/ProcessorAggregatorOptions.php, components/ImportExportBundle/src/lib/Processor/Iterator/IteratorProcessor.php, components/ImportExportBundle/src/lib/Processor/Iterator/IteratorProcessorOptions.php
=> Feat importexport iterator processor

components/ImportExportBundle/src/lib/Accessor/ArrayAccessor.php, components/ImportExportBundle/src/lib/Workflow/AbstractWorkflow.php
=> fix: writer prepare order

components/SolrSearchExtraBundle/src/bundle/Resources/config/aggregators.yml, components/SolrSearchExtraBundle/src/bundle/Resources/config/taxonomy_aggregator.yml, components/SolrSearchExtraBundle/src/lib/Query/Aggregation/RawTermAggregation.php, components/SolrSearchExtraBundle/src/lib/Query/AggregationVisitor/RawTermAggregationVisitor.php, components/SolrSearchExtraBundle/src/lib/ResultExtractor/RawTermAggregationResultExtractor.php, components/SolrSearchExtraBundle/src/lib/Search/AggregationResult/RawTermAggregationResultEntry.php
=> feat: support for nested aggregations

components/ImportExportBundle/src/lib/Item/ValueTransformer/Ibexa/TextToRichtextTransformer.php
=> fix: missing nl2br in text to richtext transformer

components/RssFeedBundle/src/bundle/Entity/RssFeeds.php
=> Fix delete Flux rss null returned

components/MenuManagerBundle/src/bundle/Controller/AdminController.php, components/MenuManagerBundle/src/bundle/Controller/ViewController.php, components/MenuManagerBundle/src/bundle/DependencyInjection/Security/Provider/MenuPolicyProvider.php, components/MenuManagerBundle/src/bundle/EzMenuManagerBundle.php, components/MenuManagerBundle/src/bundle/Resources/config/policies.yml, components/MenuManagerBundle/src/bundle/Resources/translations/menu_manager.en.yml, components/MenuManagerBundle/src/bundle/Resources/translations/menu_manager.fr.yml
=> Add role policies

components/SEOBundle/bundle/Listener/AdminTopMenu.php, components/SEOBundle/bundle/Resources/config/services.yml
=> Fix access display menu

components/ImportExportBundle/src/bundle/Controller/Admin/JobController.php, components/ImportExportBundle/src/bundle/Resources/config/menu.yaml, components/ImportExportBundle/src/bundle/Resources/config/policies.yaml, components/ImportExportBundle/src/lib/AdminUi/Menu/Event/MenuListener.php
=> Fix access permission

components/CaptchEtatBundle/src/bundle/Resources/public/js/captchetat-widget.js
=> fix: issue with captcha being added multiple time

components/MenuManagerBundle/src/lib/Exception/MenuNotFoundException.php, components/MenuManagerBundle/src/lib/Service/MenuService.php
=> feat: add exception throwing to menu service

components/CaptchEtatBundle/src/bundle/Resources/config/default_settings.yaml, components/CaptchEtatBundle/src/bundle/Resources/config/services.yaml, components/CaptchEtatBundle/src/lib/Twig/CaptchEtatExtension.php
=> feat: add a `captchetat_types_by_language` sf parameter

components/2FABundle/bundle/Controller/TwoFactorAuthController.php, components/2FABundle/bundle/Core/AuthCodeMailer.php, components/2FABundle/bundle/Core/BackupCodeManager.php, components/2FABundle/bundle/Core/EmailCodeGenerator.php, components/2FABundle/bundle/Core/SiteAccessAwareAuthenticatorResolver.php, components/2FABundle/bundle/Core/SiteAccessAwareQueryExecutor.php, components/2FABundle/bundle/Core/Tab/TwoFAManagement.php, components/2FABundle/bundle/Entity/UserTotpAuthSecret.php, components/2FABundle/bundle/Listener/UserEventSubscriber.php, components/2FABundle/bundle/Security/TwoFactorUserProviderDecorator.php
=> fix bug reset 2FA by admin

components/ImportExportBundle/src/bundle/Controller/Admin/JobController.php, components/ImportExportBundle/src/bundle/Resources/config/routes.yaml, components/ImportExportBundle/src/bundle/Resources/translations/import_export.en.yaml, components/ImportExportBundle/src/bundle/Resources/translations/import_export.fr.yaml, components/ImportExportBundle/src/bundle/Resources/views/themes/admin/import_export/job/list.html.twig, components/ImportExportBundle/src/bundle/Resources/views/themes/admin/import_export/job/view.html.twig, components/ImportExportBundle/src/lib/AdminUi/Menu/Event/MenuListener.php, components/ImportExportBundle/src/lib/Job/AbstractJobRunner.php, components/ImportExportBundle/src/lib/Job/AsyncJobRunner.php, components/ImportExportBundle/src/lib/Job/Job.php, components/ImportExportBundle/src/lib/Job/JobRunner.php, components/ImportExportBundle/src/lib/Job/JobService.php
=> fix: issue with job pause management

components/SEOBundle/bundle/Core/UrlWildcardRouter.php, components/SEOBundle/bundle/EventListener/RequestEventListener.php, components/SEOBundle/bundle/Resources/config/services.yml
=> Fix the format of parameters in the redirect URL
